Improvement fu user implementation
Wolkabout/WolkConnect-C pull request #70
Opened 2021-02-25 12:19 UTC by srdjastankovic

- Implement FU verification in connector
 - Implement ver on user space based on txt file
 - update typos

2021-02-26 14:21 UTC, LazarBozic94 requested changes

2021-02-26 14:21 UTC, LazarBozic94 commented on sources/firmware_update.c
> +    WOLK_ASSERT(status);
what is status?

2021-02-26 14:21 UTC, LazarBozic94 commented on sources/firmware_update.c
>      WOLK_ASSERT(firmware_update);
assert wolk_ctx as well?

2021-03-02 18:43 UTC, srdjastankovic commented on examples/full_feature_set/firmware_update_implementation.c
> +static bool _set_version(char* source, int8_t* version)
> Why do you start naming with an underscore?

inherit from wolk_connect.c, firmware_update.c

2021-03-02 21:22 UTC, srdjastankovic commented on examples/full_feature_set/firmware_update_implementation.c
> +            version++;
not suported format by this imeplemntation, see this:
#define FIRMWARE_UPDATE_VERSION_NUMBER_OF_ELEMENTS 3
static int8_t version_major = 0;
static int8_t version_minor = 0;
static int8_t version_patch = 1;

2021-03-02 21:23 UTC, srdjastankovic commented on examples/full_feature_set/firmware_update_implementation.c
> +                     FIRMWARE_UPDATE_VERSION_FORMAT_DELIMITER, tmp_version[1], FIRMWARE_UPDATE_VERSION_FORMAT_DELIMITER,
clang?

2021-03-02 21:26 UTC, srdjastankovic commented on examples/full_feature_set/firmware_update_implementation.c
> +        file_pointer = fopen(FIRMWARE_UPDATE_VERIFICATION_FILE_NAME, FIRMWARE_UPDATE_VERIFICATION_FILE_MODE_WRITE);
tell me which mode to use?

2021-03-03 10:44 UTC, LazarBozic94 approved these changes

2021-03-03 10:52 UTC, merged